services:
  - name: AlzAware_API
    type: web
    env: python
    region: singapore 
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --threads 8 --timeout 0
    plan: free  # Use "starter" for paid plans
    envVars:
    autoDeploy: true  